name: Run TC Auto Number

on:
  workflow_dispatch:
    inputs:
      sheet_data:
        description: 'Data from the edited sheet'
        required: true
        type: string

jobs:
  autonumber:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth

      - name: Run auto-number script
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "Running auto-number.py with sheet data..."
          python automated-test-case/auto-number.py
