name: Run TC Auto Number

on:
  workflow_dispatch:
    inputs:
      sheet_data:
        description: 'Data from the edited sheet'
        required: true
        type: string

jobs:
  autonumber:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install google-auth google-auth-httplib2 google-api-python-client pytz

      - name: Run scripts
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          python automated-test-case/autonumber.py
          python automated-test-case/auto-unmerging.py
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}
