name: Test Case Auto Number Service

on:
  workflow_dispatch:
    inputs:
      sheet_data:
        description: 'Data from the edited sheet'
        required: true
        type: string

jobs:
  autonumber:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run autonumber script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/autonumber.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}
