name: Automated Test Case Updater

on:
  workflow_dispatch:
    inputs:
      sheet_data:
        description: 'Data from the edited sheet'
        required: true
        type: string

jobs:
  autonumber:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run auto unmerge script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node unmerging-cells.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON}}

      - name: Run autonumber script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node autonumber.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON}}

      - name: Run updateToC script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node updateToC.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON}}

      - name: Run Issues Sheet Dropdown script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node issues-sheet-dropdown.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON}}
