name: Fetch GitLab Issues Service

on:
  # schedule:
  #   - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  run-github:
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow this job to fail without failing the entire workflow

    env:
      PROJECT_CONFIG: ${{ secrets.PROJECT_CONFIG }}  # ✅ Add this at job level to ensure access

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd SheetSync
          npm install

      - name: Check Runner IP Address
        run: |
          echo "Fetching IP address..."
          IP_ADDRESS=$(curl -s ifconfig.me)
          echo "Runner IP Address: $IP_ADDRESS"

      - name: Run fetchallissues.js
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          SHEET_SYNC_SID: ${{ secrets.SHEET_SYNC_SID }}
          SHEET_SYNC_SAJ: ${{ secrets.SHEET_SYNC_SAJ }}
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          PROJECT_CONFIG: ${{ secrets.PROJECT_CONFIG }}  # ✅ Pass PROJECT_CONFIG explicitly
        run: |
          cd SheetSync
          node fetchallissues.js
