name: Fetch GitLab MR Service

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  run-github:
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow this job to fail without failing the entire workflow

    env:
      PROJECT_CONFIG: ${{ secrets.PROJECT_CONFIG }}  # ✅ Set globally for the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd SheetSync
          npm install

      - name: Run fetchallmr.js
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          SHEET_SYNC_SID: ${{ secrets.SHEET_SYNC_SID }}
          SHEET_SYNC_SAJ: ${{ secrets.SHEET_SYNC_SAJ }}
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          PROJECT_CONFIG: ${{ secrets.PROJECT_CONFIG }}  # ✅ Explicitly pass this too
        run: |
          cd SheetSync
          node fetchallmr.js
