name: CDS Portals Update Service 7

on:
  workflow_dispatch:  # allows manual triggering
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Verify folder contents (for debugging)
        run: |
          ls -la automated-portals  # List contents of the folder

      - name: Run update script
        env:
          CDS_PORTALS_SERVICE_ACCOUNT_JSON: ${{ secrets.CDS_PORTALS_SERVICE_ACCOUNT_JSON }}
          CDS_PORTAL_SPREADSHEET_ID: ${{ secrets.CDS_PORTAL_SPREADSHEET_ID }}
        run: |
          cd automated-portals
          ls -la  # List files in the folder for verification
          node execute-update-request.js
