name: Send Task Reminders

on:
  schedule:
    - cron: "0 9 * * *"  # Every day at 9 AM UTC
  workflow_dispatch:     # Manual trigger allowed

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-api-python-client pytz

      - name: Run reminder script
        env:
          GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TEAM_CDS_SERVICE_ACCOUNT_JSON: ${{ secrets.TEAM_CDS_SERVICE_ACCOUNT_JSON }}
          LEADS_CDS_SID: ${{ secrets.LEADS_CDS_SID }}
          CDS_MASTER_ROSTER: ${{ secrets.CDS_MASTER_ROSTER }}
        run: python team-cds/mr-review-reminder.py
