name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      sheet_data:
        description: 'Data from the edited sheet'
        required: true
        type: string

jobs:
  start-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger next workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: "test-case-update.yml"
          ref: main  # or the appropriate branch
          inputs:
            sheet_data: ${{ github.event.inputs.sheet_data }}
