name: Automated Test Case Updater

on:
  workflow_dispatch:
    inputs:
      sheet_data:
        description: 'Data from the edited sheet'
        required: true
        type: string

concurrency:
  group: "test-case-update"
  cancel-in-progress: false  # Don't cancel an in-progress job

jobs:
  start-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger next workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: "automated-test-case/test-case-update.yml"  # Path to the workflow file inside the folder
          ref: main  # Ensure you're targeting the correct branch
          inputs:
            sheet_data: ${{ github.event.inputs.sheet_data }}
