name: Auto Number Sheets

on:
  workflow_dispatch:
    inputs:
      spreadsheetUrl:
        description: "Google Sheet URL"
        required: true
        type: string

jobs:
  autonumber:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to access the code and files
      - uses: actions/checkout@v3

      # Step 2: Debugging - Echo the passed Spreadsheet URL
      - name: Debug - Check Spreadsheet URL
        run: echo "Spreadsheet URL: ${{ github.event.inputs.spreadsheetUrl }}"

      # Step 3: Set up Node.js (ensure correct Node.js version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 4: Install project dependencies (if needed)
      - name: Install dependencies
        run: npm install

      # Step 5: Run the autonumber script
      - name: Run autonumber script
        run: node autonumber.js
        env:
          SHEET_URL: ${{ github.event.inputs.spreadsheetUrl }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

      # Step 6: Debugging - Check if the script has completed successfully
      - name: Debug - Confirm script run
        run: echo "Autonumber script has been executed."
