name: Automated Test Case Updater

on:
  workflow_dispatch:
    inputs:
      sheet_data:
        description: 'Data from the edited sheet'
        required: true
        type: string

jobs:
  autonumber:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run autonumber script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/autonumber.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}

      - name: Run updateToC script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/updateToC.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}

      - name: Run Issues Sheet Dropdown script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/issues-sheet-dropdown.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}

      - name: Run send-log script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/send-log.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}
          AUTOMATED_PORTALS: ${{ secrets.AUTOMATED_PORTALS }}

      - name: Run fetch GitLab Issues
        run: node team-cds/fetch-issues.js
        env:
          FETCH_GITLAB_ISSUES_SERVICE: ${{ secrets.FETCH_GITLAB_ISSUES_SERVICE }}

      - name: Run fetch GitLab NTC
        run: node team-cds/fetch-ntc.js
        env:
          FETCH_GITLAB_NTC_SERVICE: ${{ secrets.FETCH_GITLAB_NTC_SERVICE }}

      - name: Run fetch GitLab MRs
        run: node team-cds/fetch-mr.js
        env:
          FETCH_GITLAB_MR_SERVICE: ${{ secrets.FETCH_GITLAB_MR_SERVICE }}

  run-self-hosted:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run autonumber script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/autonumber.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}

      - name: Run updateToC script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/updateToC.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}

      - name: Run Issues Sheet Dropdown script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/issues-sheet-dropdown.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}

      - name: Run send-log script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/send-log.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}
          AUTOMATED_PORTALS: ${{ secrets.AUTOMATED_PORTALS }}

      - name: Run fetch GitLab Issues
        run: node team-cds/fetch-issues.js
        env:
          FETCH_GITLAB_ISSUES_SERVICE: ${{ secrets.FETCH_GITLAB_ISSUES_SERVICE }}

      - name: Run fetch GitLab NTC
        run: node team-cds/fetch-ntc.js
        env:
          FETCH_GITLAB_NTC_SERVICE: ${{ secrets.FETCH_GITLAB_NTC_SERVICE }}

      - name: Run fetch GitLab MRs
        run: node team-cds/fetch-mr.js
        env:
          FETCH_GITLAB_MR_SERVICE: ${{ secrets.FETCH_GITLAB_MR_SERVICE }}
