name: Auto Number Sheets

jobs:
  autonumber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug - Check Spreadsheet URL
        run: echo "Spreadsheet URL: ${{ github.event.inputs.spreadsheetUrl }}"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run autonumber script
        run: node autonumber.js
        env:
          SHEET_URL: ${{ github.event.inputs.spreadsheetUrl }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
