name: Auto Numbering

on:
  workflow_dispatch:
    inputs:
      sheet_data:
        description: 'Data from Google Sheets'
        required: true

jobs:
  auto_number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install google-spreadsheet

      - name: Run Auto Number Script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }} # Ensure this is set correctly
          INPUT_SHEET_DATA: ${{ github.event.inputs.sheet_data }} # Pass the input data to the script
          GITHUB_TOKEN: ${{ secrets.TC_TOKEN }} # Use the renamed secret name here
        run: node autoNumber.js
