name: Auto Number Sheets

on:
  workflow_dispatch:
    inputs:
      spreadsheetUrl:
        description: "The Google Sheet URL"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run autonumber script
        run: node src/autonumber.js
        env:
          SHEET_URL: ${{ github.event.inputs.spreadsheetUrl }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
