name: Automated Test Case Updater

on:
  workflow_dispatch:
    inputs:
      sheet_data:
        description: 'Data from the edited sheet'
        required: true
        type: string

concurrency:
  group: 'test-case-updater'  # Ensures all runs are part of the same group
  cancel-in-progress: false    # Do not cancel any currently running workflows. Jobs will queue up.

jobs:
  autonumber:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run autonumber script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/autonumber.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}

  updateToC:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: autonumber  # This job depends on the autonumber job to run first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run updateToC script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/updateToC.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}

  issuesSheetDropdown:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: updateToC  # This job depends on the updateToC job to run first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Issues Sheet Dropdown script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/issues-sheet-dropdown.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}

  sendLog:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: issuesSheetDropdown  # This job depends on the issuesSheetDropdown to run first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run send-log script
        run: |
          echo "Sheet Data: ${{ github.event.inputs.sheet_data }}"
          node automated-test-case/send-log.js
        env:
          SHEET_DATA: ${{ github.event.inputs.sheet_data }}
          TEST_CASE_SERVICE_ACCOUNT_JSON: ${{ secrets.TEST_CASE_SERVICE_ACCOUNT_JSON }}
          AUTOMATED_PORTALS: ${{ secrets.AUTOMATED_PORTALS }}
